### PR TITLE
changed return type of acknowledgeMeasurement from bool to void

### PR DESCRIPTION
**Pull request by kritzikratzi**
fixes MSVC error. 

this really should be an error in clang, happens to me all the time too ^^

### CODE REVIEW

**Comment by armadillu** [comment]
yeah i see those often, crazy how it skips them!

**Comment by armadillu** [comment]
if you are on window, can you try the new TSGL_START / STOP? didn't try it yet there

**Comment by kritzikratzi** [comment]
if works, but there is a bug that should also occur on MacOS: 

1. before doing anything, call `ofxTimeMeasurements::instance()->setEnabled(false);` (there's probably a neat macro for this?)
2. call TSGL_START("preview");

now you end up in a weird state. 
internally it discovers there's no entry in the map, so it forwards to startMeasurement. that in turn checks `if(!enabled) return;`, so no map entry is created, but an entry in glNames is created. 
(it also causes a crash later on, but the map state is the bigger problem i think)

maybe the simplest solution would be to also do `if(!enabled)` at the start of `startMeasuringGL`

**Comment by armadillu** [comment]
ha yep! good catch, i rushed the commit last night... there are so many states and its so messy that's hard to keep track

**Comment by kritzikratzi** [comment]
i just happend to have it disabled by default, and it crashed right away :)

**Pull request merged**
